# Generated by Django 5.1.4 on 2025-01-08 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_alter_book_author_alter_book_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='copies_available',
            new_name='number_of_copies_available',
        ),
    ]
